name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js lts/*
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Eslint
      - run: yarn install
      - run: yarn run eslint

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js lts/*
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Tests
      - run: yarn install
      - run: yarn test
      - name: Cypress artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Cypress artifacts
          path: cypress/*

  deploy:
    needs: ['eslint', 'tests']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js lts/*
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Deploy
      - run: yarn install
      - run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn run gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
